PROHIBITED_RULES = {
    "P-01": {"desc": "Conteúdo adulto ou pornográfico", "terms": ["adulto", "pornô", "xxx", "sexo"]},
    "P-02": {"desc": "Conteúdo violento ou chocante", "terms": ["violência", "sangue", "gore"]},
    "P-03": {"desc": "Discurso de ódio, discriminação ou assédio", "terms": ["ódio", "racismo", "discriminação"]},
    "P-04": {"desc": "Atividades ilegais", "terms": ["ilegal", "criminoso", "contrabando"]},
    "P-05": {"desc": "Drogas e substâncias proibidas", "terms": ["droga", "maconha", "cocaína"]},
    "P-06": {"desc": "Bebidas alcoólicas e tabaco", "terms": ["álcool", "cerveja", "tabaco"]},
    "P-07": {"desc": "Armas, munições e explosivos", "terms": ["arma", "pistola", "explosivo"]},
    "P-08": {"desc": "Conteúdo enganoso ou sensacionalista", "terms": ["milagre", "cura instantânea"]},
    "P-09": {"desc": "Fraudes e esquemas de dinheiro fácil", "terms": ["dinheiro fácil", "enriquecer rápido"]},
    "P-10": {"desc": "Clickbait excessivo", "terms": ["você não vai acreditar", "chocante"]},
    "P-11": {"desc": "Downloads ilegais", "terms": ["torrent", "download grátis"]},
    "P-12": {"desc": "Violação de direitos autorais", "terms": ["copyright", "protegido por direitos"]},
    "P-13": {"desc": "Manipulação de tráfego e cliques", "terms": ["cliques automáticos", "bot de tráfego"]},
    "P-14": {"desc": "Conteúdo duplicado ou sem valor", "terms": ["conteúdo copiado", "plágio"]},
    "P-15": {"desc": "Excesso de anúncios e pop-ups", "terms": ["popup", "anúncio intrusivo"]},
    "P-16": {"desc": "Erros graves de navegação ou design", "terms": ["erro 404", "site quebrado"]},
    "P-17": {"desc": "Hacking, cracking ou invasão de sistemas", "terms": ["hack", "crack", "invasão"]},
    "P-18": {"desc": "Fake news e desinformação", "terms": ["notícia falsa", "desinformação"]},
    "P-19": {"desc": "Afiliados sem conteúdo próprio", "terms": ["afiliado", "sem conteúdo próprio"]},
    "P-20": {"desc": "Conteúdo automatizado sem revisão humana", "terms": ["gerado automaticamente", "sem revisão"]},
    "P-21": {"desc": "Conteúdo médico duvidoso ou perigoso", "terms": ["cura milagrosa", "tratamento secreto"]},
    "P-22": {"desc": "Sites copiados ou sem identidade própria", "terms": ["cópia", "clone", "template pronto"]},
    "P-23": {"desc": "Propaganda política enganosa ou sem fontes", "terms": ["fake eleitoral", "manipulação política"]},
    "P-24": {"desc": "Idioma não suportado pelo AdSense", "terms": []},
    "P-25": {"desc": "Redirecionamentos automáticos e enganosos", "terms": ["redirecionamento oculto"]},
    "P-26": {"desc": "Malware, phishing ou códigos perigosos", "terms": ["malware", "phishing", "vírus"]},
    "P-27": {"desc": "Venda de dados pessoais", "terms": ["venda de dados", "vazar dados"]},
    "P-28": {"desc": "Conteúdo relacionado a jogos de azar e apostas", "terms": ["cassino", "aposta online", "jogo de azar"]},
    "P-29": {"desc": "Conteúdo que incita ódio a grupos ou indivíduos", "terms": ["ódio religioso", "preconceito"]},
    "P-30": {"desc": "SEO Black Hat ou spam", "terms": ["black hat", "keyword stuffing"]},
    "P-31": {"desc": "Incentivo a comportamentos perigosos", "terms": ["autolesão", "suicídio", "bulimia"]},
    "P-32": {"desc": "Falsificação de identidade ou informações", "terms": ["identidade falsa", "falsificado"]},
    "P-33": {"desc": "Venda ou troca de contas do AdSense", "terms": ["venda de conta adsense", "comprar adsense"]},
    "P-34": {"desc": "Criptomoedas ou investimentos de alto risco sem transparência", "terms": ["criptomoeda suspeita", "lucro garantido"]},
    "P-35": {"desc": "Sites que só redirecionam para outros", "terms": ["redirecionamento puro"]},
}

ALLOWED_RULES = {
    "A-01": {"desc": "Conteúdo original, útil e autoral", "terms": ["autoral", "conteúdo próprio", "guia"]},
    "A-02": {"desc": "Design responsivo e acessível", "terms": ["design responsivo", "mobile friendly"]},
    "A-03": {"desc": "Boas práticas de SEO (H1, meta, título)", "terms": ["h1", "meta", "title"]},
    "A-04": {"desc": "Política de privacidade visível", "terms": ["política de privacidade"]},
    "A-05": {"desc": "Página de contato e informações claras", "terms": ["fale conosco", "contato", "email de suporte"]},
    "A-06": {"desc": "Termos de uso e transparência", "terms": ["termos de uso", "responsabilidade"]},
    "A-07": {"desc": "Atualizações frequentes e revisões", "terms": ["atualizado em", "última revisão"]},
    "A-08": {"desc": "Navegação intuitiva e menus organizados", "terms": ["menu", "categorias claras"]},
    "A-09": {"desc": "Boa ortografia e gramática", "terms": []},
    "A-10": {"desc": "Carregamento rápido e código otimizado", "terms": ["pagespeed", "carregamento rápido"]},
    "A-11": {"desc": "Imagens com texto alternativo (ALT)", "terms": ["alt=", "descrição de imagem"]},
    "A-12": {"desc": "Blog ou seção de conteúdo útil", "terms": ["blog", "artigos", "notícias"]},
    "A-13": {"desc": "Links externos confiáveis e bem referenciados", "terms": ["fonte:", "referência"]},
    "A-14": {"desc": "Conteúdo com mais de 300 palavras por página", "terms": []},
    "A-15": {"desc": "Sem excesso de anúncios", "terms": []},
    "A-16": {"desc": "URLs amigáveis e organizadas", "terms": ["slug", "/dicas/", "/artigos/"]},
    "A-17": {"desc": "Conteúdo multimídia relevante (vídeos, áudios)", "terms": ["youtube", "vídeo explicativo"]},
    "A-18": {"desc": "Links internos entre páginas relevantes", "terms": ["leia também", "veja mais"]},
    "A-19": {"desc": "Conteúdo com linguagem clara e objetiva", "terms": ["simples", "claro", "objetivo"]},
    "A-20": {"desc": "Confiança e reputação (ex: HTTPS, domínio limpo)", "terms": ["https", "site seguro"]},
}
